# Generated by Django 2.2.5 on 2019-09-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('code', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='api.Region')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code_insee', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('population', models.FloatField(null=True)),
                ('area', models.FloatField(null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.County')),
            ],
        ),
    ]
