# Generated by Django 2.2.5 on 2019-09-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=9, null=True),
        ),
    ]
